In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras # type: ignore

### Exercise 1: Regression - Optimize

In [43]:
from keras.layers import Dense # type: ignore
model = keras.Sequential()
model.add(Dense(8, input_shape=(5,), activation= 'sigmoid'))
model.add(Dense(4, activation= 'sigmoid'))
model.add(Dense(1, activation= 'linear'))

##### 1. Fill this chunk of code to set up the optimization part of the regression neural network:

In [44]:
model.compile(
  optimizer='adam',
  loss='mse', 
  metrics=['mae']
)



### Exercise 2: Regression example

In [45]:
df = pd.read_csv('https://raw.githubusercontent.com/01-edu/public/refs/heads/master/subjects/ai/keras-2/auto-mpg.csv',na_values=["?"])

##### 1. Data preprocessing

In [46]:
df.drop(['model year', 'origin', 'car name'], axis=1,inplace=True)
df.dropna(inplace=True)
from sklearn.model_selection import train_test_split

X,y = df.drop("mpg",axis=1),df.mpg

from sklearn.preprocessing import StandardScaler
from keras.models import Sequential # type: ignore
from keras.layers import Dense # type: ignore

# Drop the columns: model year, origin, car name (already done)
# Split train test without shuffling the data. Keep 20% for the test set.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# Scale the data using Standard Scaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train a neural network on the train set
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')

# Train the model with increased epochs
model.fit(X_train_scaled, y_train, epochs=100, verbose=0)

# Predict on the test set
y_pred = model.predict(X_test_scaled)

# Evaluate the model on the scaled test set
mse = model.evaluate(X_test_scaled, y_test, verbose=0)

from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,y_pred)


3/3 [==============================] - 0s 14ms/step


In [47]:
print(X_train_scaled.shape)
print(X_train_scaled[:5])

(313, 5)
[[ 1.28377043  0.88466635  0.4869698   0.45570808 -1.19481335]
 [ 1.28377043  1.28127292  1.36238071  0.67045896 -1.37736562]
 [ 1.28377043  0.98612384  0.98720461  0.37844321 -1.55991789]
 [ 1.28377043  0.85699612  0.98720461  0.37503446 -1.19481335]
 [ 1.28377043  0.8385493   0.7370872   0.39321443 -1.74247016]]


In [48]:
print(y_train[:5])
print(X_test_scaled[:5])
print(y_test[:5])
print(f'Mean Absolute Error: {mae:.2f}')

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: mpg, dtype: float64
[[-1.00254618 -0.55418542 -0.51349982 -0.1135522   1.76253341]
 [ 0.14061212  0.12834683 -0.51349982  0.31594957  1.25138706]
 [-1.00254618 -1.0522495  -0.81364071 -1.03959438  0.1925839 ]
 [-1.00254618 -0.71098337 -0.51349982 -0.44533664  0.08305253]
 [-1.00254618 -0.84011109 -0.88867593 -0.63736256  0.81326161]]
315    24.3
316    19.1
317    34.3
318    29.8
319    31.3
Name: mpg, dtype: float64
Mean Absolute Error: 6.25


### Exercise 3: Multi classification - Softmax

In [49]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Create the model
model = Sequential()

# Add the input layer and the first hidden layer
model.add(Dense(16, activation='sigmoid', input_shape=(5,)))

# Add the second hidden layer
model.add(Dense(8, activation='sigmoid'))

# Add the output layer with 5 neurons (one for each class) and softmax activation function
model.add(Dense(5, activation='softmax'))

# Print the model summary
print(model.summary())



Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_36 (Dense)            (None, 16)                96        
                                                                 
 dense_37 (Dense)            (None, 8)                 136       
                                                                 
 dense_38 (Dense)            (None, 5)                 45        
                                                                 
Total params: 277
Trainable params: 277
Non-trainable params: 0
_________________________________________________________________
None


### Exercise 4: Multi classification - Optimize

In [50]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam', 
              metrics=['accuracy'])



### Exercise 5 Multi classification example

In [53]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelBinarizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load the dataset from sklearn
iris = datasets.load_iris()

# Split train test. Keep 20% for the test set. Use random_state=1
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=1)

# Scale the data using Standard Scaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Use the LabelBinarizer from Sckit-learn to create a one hot encoding of the target
lb = LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

# Train a neural network on the train set and predict on the test set
model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(4,)))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=10, verbose=0)
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f'Test accuracy: {accuracy:.2f}')



Test accuracy: 0.97
