### Exercise 0: Environment and libraries

In [1]:
print("Buy the dip ?")

Buy the dip ?


### Exercise 1: Your first NumPy array

1. import numpy

In [2]:
import numpy as np

2. create an array with numpy (important: add ```dtype=object``` for an array with differents data types) 

In [3]:
arr = np.array([5, 0.5, "5", {"value":5}, [1,2,3,4,5], (1,2,3,4,5), {1,2,3,4,5},True],dtype=object)

3. Prnt data type of each value in arr

In [4]:
for i in arr:
    print(type(i))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


### Exercise 2: Zeros

1. Create a NumPy array of dimension 300 with zeros without filling it manually

In [5]:
arr = np.zeros(300)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

2. Reshape it to (3,100)
- this mean convert the array `arr` to a 3d array contain

In [6]:
reshapearr =arr.reshape(3,100)
reshapearr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.

### Exercise 3: Slicing

1. Create a NumPy array of dimension 1 that contains all integers from 1 to 100 ordered.

In [7]:
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

2. Without using a for loop and using the array created in Q1, create an array that contain all odd integers. The expected output is:

In [8]:
oddarr = arr[arr%2!=0]
oddarr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

3. Without using a for loop and using the array created in Q1, create an array that contain all even integers reversed. The expected output is:

In [9]:
evenRevArr = np.flip(arr[arr%2==0])
evenRevArr

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6,   4,   2])

4. Using array of Q1, set the value of every 3 elements of the list (starting with the second) to 0. The expected output is:


In [10]:
arr[1::3] = 0
arr

array([  1,   0,   3,   4,   0,   6,   7,   0,   9,  10,   0,  12,  13,
         0,  15,  16,   0,  18,  19,   0,  21,  22,   0,  24,  25,   0,
        27,  28,   0,  30,  31,   0,  33,  34,   0,  36,  37,   0,  39,
        40,   0,  42,  43,   0,  45,  46,   0,  48,  49,   0,  51,  52,
         0,  54,  55,   0,  57,  58,   0,  60,  61,   0,  63,  64,   0,
        66,  67,   0,  69,  70,   0,  72,  73,   0,  75,  76,   0,  78,
        79,   0,  81,  82,   0,  84,  85,   0,  87,  88,   0,  90,  91,
         0,  93,  94,   0,  96,  97,   0,  99, 100])

### Exercise 4: Random

1. Set the seed to 888

In [11]:
np.random.seed(888)

2. Generate a one-dimensional array of size 100 with a normal distribution

In [12]:
randArr = np.random.randn(100)
randArr

array([-1.76200874e-01,  1.88876361e-01,  8.26747180e-01, -3.24473146e-02,
       -6.52499418e-01, -1.05339382e-01,  2.17776116e-01,  5.87281504e-01,
        1.00237892e-01, -1.09994668e+00, -2.55305389e-01,  4.05304381e-01,
        1.62663953e-01,  1.04163462e+00,  2.24324184e-01,  6.99304449e-01,
       -8.65543512e-01, -1.39346831e+00, -2.36687913e-01, -7.57041911e-01,
        1.31429195e+00, -9.77385899e-01, -3.59032576e-01,  1.16141585e-01,
       -3.51081138e-01, -4.39838344e-01, -4.90995473e-02, -4.31596770e-01,
       -1.08875099e+00, -2.31088106e+00, -1.86236420e+00,  2.34708674e-01,
       -8.95585921e-01, -5.40834525e-01, -4.02399061e-01,  2.31458561e-02,
        1.77688506e-01, -5.73309272e-01, -3.38392138e-01, -2.64422114e-03,
        1.44930339e+00,  1.36605641e+00,  2.69187461e+00,  6.76065035e-01,
       -1.06098418e+00,  1.31845313e-01,  1.71934297e-01,  8.88062794e-02,
        1.03963016e+00, -1.37846942e-01, -3.69232844e-01,  3.19587912e+00,
        1.11457451e+00, -

3. Generate a two-dimensional array of size 8,8 with random integers from 1 to 10 - both included (same probability for each integer)

In [13]:
rand2dArr = np.random.randint(1,11,size=(8,8))
rand2dArr

array([[ 9,  8,  4,  6,  9,  1,  3,  2],
       [ 3,  9,  9,  5,  4,  7,  2,  8],
       [ 5,  6,  9,  1,  1,  6,  8,  7],
       [ 7,  1,  4,  1, 10,  4,  3,  5],
       [ 5, 10,  1, 10,  7, 10,  6,  1],
       [ 6,  8,  7,  4,  6, 10,  3,  5],
       [ 4, 10,  7,  9,  9, 10,  9,  9],
       [ 5,  3,  2, 10,  8,  5,  5,  3]])

4. Generate a three-dimensional of size 4,2,5 array with random integers from 1 to 17 - both included (same probability for each integer)

In [14]:
rand3dArr = np.random.randint(1,high=18,size=(4,2,5))
rand3dArr


array([[[ 5,  2, 13, 16, 15],
        [ 5,  5,  2, 11,  3]],

       [[ 8, 13,  6,  4, 17],
        [ 2,  8,  1, 13, 10]],

       [[12, 17, 17, 12,  1],
        [10,  8, 17,  5, 11]],

       [[ 9, 14,  2, 15, 13],
        [12, 14,  6, 14,  2]]])

### Exercise 5: Split, concatenate, reshape arrays

1. Generate an array with integers from 1 to 50: array([1,...,50])

In [15]:
arr50 = np.arange(1,51)
arr50

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

2. Generate an array with integers from 51 to 100: array([51,...,100])

In [16]:
arr100 = np.arange(51,101)
arr

array([  1,   0,   3,   4,   0,   6,   7,   0,   9,  10,   0,  12,  13,
         0,  15,  16,   0,  18,  19,   0,  21,  22,   0,  24,  25,   0,
        27,  28,   0,  30,  31,   0,  33,  34,   0,  36,  37,   0,  39,
        40,   0,  42,  43,   0,  45,  46,   0,  48,  49,   0,  51,  52,
         0,  54,  55,   0,  57,  58,   0,  60,  61,   0,  63,  64,   0,
        66,  67,   0,  69,  70,   0,  72,  73,   0,  75,  76,   0,  78,
        79,   0,  81,  82,   0,  84,  85,   0,  87,  88,   0,  90,  91,
         0,  93,  94,   0,  96,  97,   0,  99, 100])

3. Using np.concatenate, concatenate the two arrays into: array([1,...,100])

In [17]:
concatarr = np.concatenate((arr50,arr100))
concatarr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

4. Reshape the previous array into:

In [18]:
concatarr.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

### Exercise 6: Broadcasting and Slicing

* Generate a 2-dimensional array of size 9x9, with all elements initialized to 1 and of type int8.

In [19]:
arr_ones = np.ones((9,9))
arr_ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

* Using slicing, create the following array:

In [20]:
arr_ones1 = arr_ones.copy()
arr_ones1[1:8, 1:8] = 0
arr_ones1[2:7:4, 2:7] = 1
arr_ones1[2:7, 2:7:4] = 1
arr_ones1[4,4] = 1
arr_ones1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

* Using broadcasting create an output matrix based on the following two arrays:

In [21]:
array_1 = np.array([1,2,3,4,5], dtype=np.int8)
array_1
array_2 = np.array([1,2,3], dtype=np.int8)
array_2

np.outer(array_1,array_2)

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15]], dtype=int8)

### Exercise 7: NaN

1. The goal of this exercise is to handle missing data in NumPy and manipulate arrays effectively.

Let's consider a 2-dimensional array containing grades from the last two exams. Some students missed the first exam, so their grades are replaced with NaN.

To simulate this scenario, we'll create a mock dataset using NumPy. Here's a snippet of code to generate this dataset:

In [22]:
import numpy as np

generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))
grades[[1,2,5,7], [0,0,0,0]] = np.nan
print(grades)


[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [nan  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [ 8.  5.]]


2. Using np.where, create a third column that takes the grade of the first exam if available; otherwise, it uses the grade from the second exam. Add this column as the third column of the array.


In [23]:
thirdcols = np.where(np.isnan(grades[:,0]), grades[:,1],grades[:,0])
thirdcols
np.column_stack((grades,thirdcols))

array([[ 7.,  1.,  7.],
       [nan,  2.,  2.],
       [nan,  8.,  8.],
       [ 9.,  3.,  9.],
       [ 8.,  9.,  8.],
       [nan,  2.,  2.],
       [ 8.,  2.,  8.],
       [nan,  6.,  6.],
       [ 9.,  2.,  9.],
       [ 8.,  5.,  8.]])

### Exercise 8: Wine

1. Load the data using genfromtxt, specifying the delimiter as ';', and optimize the numpy array size by reducing the data types. Use np.float32 and verify that the resulting numpy array weighs 76800 bytes.

In [24]:
data = np.genfromtxt("data/winequality-red.csv",delimiter=';',dtype=np.float32)
data.nbytes

76800

2. Display the 2nd, 7th, and 12th rows as a two-dimensional array. Exclude np.nan values if present.

In [25]:
filteredData = data[np.array([1,6,11])]
filteredData

array([[ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
         0.9978,  3.51  ,  0.56  ,  9.4   ,  5.    ],
       [ 7.4   ,  0.66  ,  0.    ,  1.8   ,  0.075 , 13.    , 40.    ,
         0.9978,  3.51  ,  0.56  ,  9.4   ,  5.    ],
       [ 6.7   ,  0.58  ,  0.08  ,  1.8   ,  0.097 , 15.    , 65.    ,
         0.9959,  3.28  ,  0.54  ,  9.2   ,  5.    ]], dtype=float32)

3. Determine if there is any wine in the dataset with an alcohol percentage greater than 20%. Return True or False.

In [26]:
alcohol = data[1:,10]
np.any(alcohol > 20)

np.False_

4. Calculate the average alcohol percentage across all wines in the dataset. Exclude np.nan values if present.

In [27]:
np.average(alcohol)

np.float32(10.422984)

5. Compute various statistical measures (minimum, maximum, 25th percentile, 50th percentile, 75th percentile and the mean for the pH values).

In [28]:
pHcol = data[1:,8]

#min pH
minpH = min(pHcol)

#max pH
maxpH = max(pHcol)

#mean
mean = np.mean(pHcol)

#25th percentil
perc25 = np.percentile(pHcol,25)

#50th percentile
perc50 = np.percentile(pHcol,50)

#75th percentile
perc75 = np.percentile(pHcol,75)

print(f"""
minimum PH: {minpH:.2f}
maximum pH {maxpH:.2f}
mean: {mean:.2f}
25th percentile: {perc25:.2f}
50th percentile: {perc50:.2f}
75th percentile: {perc75:.2f}
""")


minimum PH: 2.74
maximum pH 4.01
mean: 3.31
25th percentile: 3.21
50th percentile: 3.31
75th percentile: 3.40



6.  Find the average quality score of wines with the 20% least sulphate content.

In [29]:
sulf = data[1:,9]
quality = data[1:,11]

#20th s0lf percentil
perc20sulf = np.percentile(sulf,20)

#sulfate lower that 20%
lowersulf = quality[sulf<= perc20sulf ]


sulfmean = np.average(lowersulf)
print(f"{sulfmean:.1f}")



5.2


7. Compute the mean of all variables for wines with the best quality. Also, do the same for wines with the worst quality.

In [30]:
#max wine quality
maxquality = max(quality)

#min wine quality
minquality = min(quality)
#max quality mask 
maxqualitymask = quality == maxquality
#max quality mask 
minqualitymask = quality == minquality

maxqualitywine = data[1:][maxqualitymask]
minqualitywine = data[1:][minqualitymask]

#mean best quality
meanbest= np.mean(maxqualitywine,axis=0)

#mean worst quality
meanworst= np.mean(minqualitywine,axis=0)

print(f"""
mean best wine quality:
{meanbest}
mean worst wine quality:
{meanworst}
""")



mean best wine quality: [ 8.566666    0.4233333   0.39111114  2.5777776   0.06844445 13.277778
 33.444443    0.99521226  3.2672222   0.76777774 12.094444    8.        ]
mean worst wine quality: [ 8.359999    0.8845      0.17099999  2.6350002   0.12249999 11.
 24.9         0.997464    3.398       0.57000005  9.955       3.        ]



## Exercise 9: Football tournament

* Load the data

In [31]:
fdata = np.genfromtxt("data/model_forecasts.txt",delimiter=",")

import itertools

teams= np.arange(fdata.shape[0])
perm = np.array(list(itertools.permutations(teams)))

perm.shape

(3628800, 10)

In [32]:
def diff_calc(perm):
    matchindices = np.arange(0,len(perm),2)
    
    team1indices =  perm[matchindices]
    team2indices = perm[matchindices+1]
    
    validindices = ~np.isnan(fdata[team1indices,team2indices])
    difference = fdata[team1indices,team2indices][validindices]
    
    return np.sum(difference ** 2)

2. calculate the squared difference

In [33]:
diffsquared = np.apply_along_axis(diff_calc,1,perm)

In [34]:
mindiffsquaredindices = np.argmin(diffsquared)
mindiff = perm[mindiffsquaredindices]

In [35]:
mindices = np.arange(0,len(mindiff),2)
t1indices = mindiff[mindices]
t2indices = mindiff[mindices+1]

r = np.array([t1indices,t2indices])
r

array([[0, 1, 2, 3, 5],
       [8, 7, 9, 4, 6]])